name: CI/CD Spring Web App

on:
  push:
    branches: [main]

jobs:
  build-and-publisher:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
       uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
         java-version: '11'
         distribution: 'adopt'
      
      - name: Install Maven Dependence
        run: mvn install

      - name: Run test & Generate Jar Package
        run: mvn --batch-mode verify

      - name: Login Docker
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Buil and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: afreire75/BETA:1 