name: CI/CD Spring Web App

on:
  push:
    branches: [main]

jobs:
  build-and-publish:

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
        
      - name: Install Maven dependencies
        run: mvn install
      
      - name: Run test & Generate Jar Package
        run: mvn --batch-mode verify

      - name: Login Docker
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Buil and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: afreire75/spring-bmi-calc:latest

      - name: Deploy to production
        uses: appleboy/ssh-action@v1.0.3
        with:
            #configuracion para AWS.
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.PASSWORD }}
            script: |
              docker stop spring-bmi-calc
              docker rm spring-bmi-calc
              docker run --pull always -d -p 80:8000 afreire75/spring-bmi-calc:latest
        
